FROM debian:bookworm

ARG TARGETPLATFORM
ENV TZ=Asia/Shanghai

RUN apt-get update && apt-get install -y ca-certificates tzdata gosu && \
    ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    rm -rf /var/cache/apt/*  && \
    mkdir -p /app

COPY build/docker/${TARGETPLATFORM}/octopus /app/octopus
COPY build/docker/${TARGETPLATFORM}/sing-box /app/bin/sing-box
COPY build/docker/${TARGETPLATFORM}/sing-box-LICENSE /usr/share/doc/sing-box/LICENSE
COPY scripts/dockerfiles/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh /app/bin/sing-box

CMD ["/entrypoint.sh"]
